language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - PEEWEE='peewee>=2.2.0,<2.3.0' DB=postgresql
  - PEEWEE='peewee>=2.2.0,<2.3.0' DB=mysql
  - PEEWEE='peewee>=2.3.0,<2.4.0' DB=postgresql
  - PEEWEE='peewee>=2.3.0,<2.4.0' DB=mysql
  - PEEWEE='peewee>=2.4.0,<2.5.0' DB=postgresql
  - PEEWEE='peewee>=2.4.0,<2.5.0' DB=mysql
  - PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=postgresql
  - PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=mysql
  - PONY='https://github.com/ponyorm/pony/archive/0.6rc2.tar.gz' DB=postgresql
  - PONY='https://github.com/ponyorm/pony/archive/0.6rc2.tar.gz' DB=mysql
  - SQLALCHEMY='sqlalchemy>=0.8.0,<0.9.0' DB=postgresql
  - SQLALCHEMY='sqlalchemy>=0.8.0,<0.9.0' DB=mysql
  - SQLALCHEMY='sqlalchemy>=0.9.0,<0.10.0' DB=postgresql
  - SQLALCHEMY='sqlalchemy>=0.9.0,<0.10.0' DB=mysql
  - DJANGO='django>=1.4.0,<1.5.0' DB=postgresql
  - DJANGO='django>=1.4.0,<1.5.0' DB=mysql
  - DJANGO='django>=1.5.0,<1.6.0' DB=postgresql
  - DJANGO='django>=1.5.0,<1.6.0' DB=mysql
  - DJANGO='django>=1.6.0,<1.7.0' DB=postgresql
  - DJANGO='django>=1.6.0,<1.7.0' DB=mysql
  - DJANGO='django>=1.7.0,<1.8.0' DB=postgresql
  - DJANGO='django>=1.7.0,<1.8.0' DB=mysql
matrix:
  fast_finish: true
  exclude:
    - python: 2.6
      env: DJANGO='django>=1.7.0,<1.8.0' DB=postgresql
    - python: 2.6
      env: DJANGO='django>=1.7.0,<1.8.0' DB=mysql
    - python: 3.2
      env: DJANGO='django>=1.4.0,<1.5.0' DB=postgresql
    - python: 3.2
      env: DJANGO='django>=1.4.0,<1.5.0' DB=mysql
    - python: 3.3
      env: DJANGO='django>=1.4.0,<1.5.0' DB=postgresql
    - python: 3.3
      env: DJANGO='django>=1.4.0,<1.5.0' DB=mysql
    - python: 3.4
      env: DJANGO='django>=1.4.0,<1.5.0' DB=postgresql
    - python: 3.4
      env: DJANGO='django>=1.4.0,<1.5.0' DB=mysql
    - python: 3.2
      env: PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=postgresql
    - python: 3.2
      env: PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=mysql
    - python: 3.3
      env: PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=postgresql
    - python: 3.3
      env: PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=mysql
    - python: 3.4
      env: PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=postgresql
    - python: 3.4
      env: PONY='pony>=0.5.0,<0.6.0,!=0.5.4' DB=mysql
    - python: 3.2
      env: PONY='https://github.com/ponyorm/pony/archive/0.6rc2.tar.gz' DB=postgresql
    - python 3.2:
      env: PONY='https://github.com/ponyorm/pony/archive/0.6rc2.tar.gz' DB=mysql
  allow_failures:
    - env: PONY='https://github.com/ponyorm/pony/archive/0.6rc2.tar.gz' DB=postgresql
    - env: PONY='https://github.com/ponyorm/pony/archive/0.6rc2.tar.gz' DB=mysql
before_script:
  - if [[ $DB == postgresql ]]; then psql -c 'create database architect;' -U postgres; fi
  - if [[ $DB == mysql ]]; then mysql -e 'create database architect;' -u root; fi
install:
  - travis_retry pip install -r tests/requirements.txt
  - travis_retry pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install unittest2 argparse; fi
  - if [[ $DB == postgresql ]]; then travis_retry pip install psycopg2; fi
  - if [[ $DB == mysql ]]; then travis_retry pip install pymysql; fi
  - if [[ $DJANGO ]]; then travis_retry pip install $DJANGO; fi
  - if [[ $PEEWEE ]]; then travis_retry pip install $PEEWEE; fi
  - if [[ $PONY ]]; then travis_retry pip install $PONY; fi
  - if [[ $SQLALCHEMY ]]; then travis_retry pip install $SQLALCHEMY; fi
script:
  - nosetests --with-coverage --cover-erase --cover-package=architect
after_success:
  - coveralls
