language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - PEEWEE='peewee>=2.2,<2.2.99' DB=postgresql
  - PEEWEE='peewee>=2.2,<2.2.99' DB=mysql
  - PONY='pony>=0.5,<0.5.99' DB=postgresql
  - PONY='pony>=0.5,<0.5.99' DB=mysql
  - SQLALCHEMY='sqlalchemy>=0.8,<0.8.99' DB=postgresql
  - SQLALCHEMY='sqlalchemy>=0.8,<0.8.99' DB=mysql
  - SQLALCHEMY='sqlalchemy>=0.9,<0.9.99' DB=postgresql
  - SQLALCHEMY='sqlalchemy>=0.9,<0.9.99' DB=mysql
  - DJANGO='django>=1.4,<1.4.99' DB=postgresql
  - DJANGO='django>=1.4,<1.4.99' DB=mysql
  - DJANGO='django>=1.5,<1.5.99' DB=postgresql
  - DJANGO='django>=1.5,<1.5.99' DB=mysql
  - DJANGO='django>=1.6,<1.6.99' DB=postgresql
  - DJANGO='django>=1.6,<1.6.99' DB=mysql
  - DJANGO=https://www.djangoproject.com/download/1.7c1/tarball DB=postgresql
  - DJANGO=https://www.djangoproject.com/download/1.7c1/tarball DB=mysql
matrix:
  exclude:
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.7c1/tarball DB=postgresql
    - python: 2.6
      env: DJANGO=https://www.djangoproject.com/download/1.7c1/tarball DB=mysql
    - python: 3.2
      env: PONY='pony>=0.5,<0.5.99' DB=postgresql
    - python: 3.2
      env: PONY='pony>=0.5,<0.5.99' DB=mysql
    - python: 3.2
      env: DJANGO='django>=1.4,<1.4.99' DB=postgresql
    - python: 3.2
      env: DJANGO='django>=1.4,<1.4.99' DB=mysql
    - python: 3.3
      env: PONY='pony>=0.5,<0.5.99' DB=postgresql
    - python: 3.3
      env: PONY='pony>=0.5,<0.5.99' DB=mysql
    - python: 3.3
      env: DJANGO='django>=1.4,<1.4.99' DB=postgresql
    - python: 3.3
      env: DJANGO='django>=1.4,<1.4.99' DB=mysql
    - python: 3.4
      env: PONY='pony>=0.5,<0.5.99' DB=postgresql
    - python: 3.4
      env: PONY='pony>=0.5,<0.5.99' DB=mysql
    - python: 3.4
      env: DJANGO='django>=1.4,<1.4.99' DB=postgresql
    - python: 3.4
      env: DJANGO='django>=1.4,<1.4.99' DB=mysql
before_script:
  - if [[ $DB == postgresql ]]; then psql -c 'create database architect;' -U postgres; fi
  - if [[ $DB == mysql ]]; then mysql -e 'create database architect;' fi
install:
  - pip install -r tests/requirements.txt
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 argparse; fi
  - if [[ $DB == postgresql ]]; then pip install psycopg2; fi
  - if [[ $DB == mysql ]]; then pip install pymysql; fi
  - if [[ $DJANGO ]]; then pip install $DJANGO; fi
  - if [[ $PEEWEE ]]; then pip install $PEEWEE; fi
  - if [[ $PONY ]]; then pip install $PONY; fi
  - if [[ $SQLALCHEMY ]]; then pip install $SQLALCHEMY; fi
script:
  - nosetests --with-coverage --cover-erase --cover-package=architect
after_success:
  - coveralls
